name: Pull-Request-Dependency

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
    tags-ignore:
      - "**"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "get refs"
        id: vars
        run: |
          echo ::set-output name=base_ref::${{ github.event.pull_request.base.ref || github.ref }}
          echo ::set-output name=head_ref::${{ github.event.pull_request.head.ref || github.ref }}

      - name: Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high
          base-ref: ${{steps.vars.outputs.base_ref}}
          head-ref: ${{steps.vars.outputs.head_ref}}
