name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: AI Code Reviewer
        uses: levyitay/mobile-api-lib-js@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          exclude: "**/*.json, **/*.md"
