name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
