name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
      - name: AI Code Reviewer
        uses: levyitay/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
          exclude: "**/*.json, **/*.md"
